"""SLIDES — render an outline to a real .pptx. Native (python-pptx).

Design reference: Presenton (Apache-2.0). No Presenton code or service is used.
Content generation (turning a prompt into an outline) is a pluggable LLM step;
this engine renders whatever outline it is given, so it works with zero config.
"""

from __future__ import annotations

from pathlib import Path

from pptx import Presentation
from zeropark_core.capabilities import Capability
from zeropark_core.models import Artifact, TaskRequest, TaskResult, TaskStatus

from zeropark_engines.base import NativeEngine

_PPTX_MIME = "application/vnd.openxmlformats-officedocument.presentationml.presentation"


class PptxSlidesEngine(NativeEngine):
    id = "pptx-slides"
    name = "PPTX Slides (python-pptx)"
    capabilities = frozenset({Capability.SLIDES})
    reference = "Presenton (Apache-2.0) - design reference only"

    def __init__(self, *, output_dir: str = "artifacts") -> None:
        self.output_dir = Path(output_dir)

    async def cap_slides(self, task: TaskRequest, task_id: str) -> TaskResult:
        # outline: [{"title": str, "bullets": [str, ...]}, ...]
        outline = task.params.get("outline") or [
            {"title": task.params.get("title") or task.prompt[:80], "bullets": []}
        ]
        deck_title = task.params.get("title") or outline[0].get("title") or task.prompt[:80]

        prs = Presentation()
        title_slide = prs.slides.add_slide(prs.slide_layouts[0])
        title_slide.shapes.title.text = deck_title
        if len(title_slide.placeholders) > 1:
            title_slide.placeholders[1].text = task.params.get("subtitle", "Generated by Zeropark")

        for item in outline:
            slide = prs.slides.add_slide(prs.slide_layouts[1])
            slide.shapes.title.text = item.get("title", "")
            bullets = item.get("bullets", []) or []
            if bullets and len(slide.placeholders) > 1:
                body = slide.placeholders[1].text_frame
                body.text = str(bullets[0])
                for bullet in bullets[1:]:
                    body.add_paragraph().text = str(bullet)

        self.output_dir.mkdir(parents=True, exist_ok=True)
        path = self.output_dir / f"{task_id}.pptx"
        prs.save(str(path))

        n_slides = len(outline) + 1
        artifact = Artifact(
            id=self.new_id("deck"),
            kind="deck",
            title=deck_title,
            mime_type=_PPTX_MIME,
            uri=str(path),
            metadata={"slides": n_slides},
        )
        return TaskResult(
            task_id=task_id,
            status=TaskStatus.SUCCEEDED,
            capability=Capability.SLIDES,
            provider_id=self.id,
            artifacts=[artifact],
            metrics={"slides": n_slides},
        )
